export default {
  titleFontSize: 25,
  primaryFontSize: 18,
  secondaryFontSize: 16,
  ternaryFontSize: 14,
  headerTopMargin: 20,
  marginBottom: 40,
  padding: 10,
  cardWidth: 100,
  cardHeight: 150,
  imageWidth: 200,
  imageHeight: 200,
  floatingButtonHeight: 50,
  floatingButtonWidth: 50,
  datePickerWidth: 300,
  primarySpacing: 30,
  primaryHeight: 50,
  headerImageHeight: 80,
}
